### ISSUE TITLE
Excuse me?

### ISSUE THREAD

**Issue by 820183398** [GayPig/driverless-basic-driver#2]
Thank you very much for sharing the code.，ButI got a BSOD from function  “clean_piddb_cache()”.I am a novice，I used the usual way to create symbolic links，Can't be created successfully.Can you tell me how to solve these two problems? Anyway, thank you very much.

**Comment by GayPig** [comment]
> Thank you very much for sharing the code.，ButI got a BSOD from function “clean_piddb_cache()”.I am a novice，I used the usual way to create symbolic links，Can't be created successfully.Can you tell me how to solve these two problems? Anyway, thank you very much.

clean piddbcache were tested only on win10 1803, probably pattern is wrong for your windows

**Comment by 820183398** [comment]
I got a BSOD from function “clean_piddb_cache()”on win7，But it works on Win10,Thank you very much.
